# Generated by Django 4.2.2 on 2023-06-05 16:51

import django.core.validators
from django.db import migrations, models
import my_music_app_pre_exam.mymusicapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusicapp', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), my_music_app_pre_exam.mymusicapp.models.validate_username]),
        ),
    ]
