# Generated by Django 4.2.2 on 2023-06-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='booK_type',
            new_name='book_type',
        ),
    ]
