# Generated by Django 4.2.2 on 2023-06-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCBV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='displacement',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
