# Generated by Django 3.2.3 on 2023-07-12 17:46

from django.db import migrations, models
import django.db.models.deletion
import lost_and_found.objects_posts.vallidators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', models.URLField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('author_name', models.CharField(max_length=10)),
                ('author_phone', models.CharField(max_length=10, validators=[lost_and_found.objects_posts.vallidators.validate_phone])),
                ('found', models.BooleanField(default=False)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects_posts.object')),
            ],
        ),
    ]
