# Generated by Django 4.2.1 on 2023-05-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=15)),
                ('city_population', models.IntegerField()),
                ('city_image', models.ImageField(upload_to='django_templates_exercise/cities/static/media/')),
            ],
        ),
    ]
