# Generated by Django 4.2.1 on 2023-06-04 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=35)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_type', models.CharField(max_length=30)),
                ('ship_name', models.CharField(max_length=30)),
                ('ship_length', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('street', models.TextField()),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='first name', max_length=30)),
                ('last_name', models.CharField(default='last name', max_length=30)),
                ('worker_age', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('experience', models.PositiveIntegerField()),
                ('worker_rang', models.CharField(choices=[('BEG', 'BEGINNER'), ('NOR', 'NORMAL'), ('SEN', 'SENIOR'), ('SUP', 'SUPERVISOR'), ('MAN', 'PRODUCTION MANAGER')], max_length=30)),
                ('start_work', models.DateTimeField(auto_now_add=True)),
                ('update_status', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipyard.workeraddress')),
                ('department', models.ManyToManyField(to='shipyard.department')),
                ('working_project', models.ManyToManyField(to='shipyard.shipproject')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
