# Generated by Django 4.2.2 on 2023-06-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FruitipediaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='age',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
    ]
