# Generated by Django 4.2.2 on 2023-06-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
