# Generated by Django 4.2.2 on 2023-06-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_plant', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(blank=True, default='/staticfiles/images/default.jpg'),
        ),
    ]
