# Generated by Django 4.2.2 on 2023-06-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='text',
            field=models.CharField(error_messages={'unique': 'The name is already taken.'}, max_length=100, unique=True),
        ),
    ]
