# Generated by Django 4.2.1 on 2023-05-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biker_name', models.CharField(max_length=30)),
                ('bike_brand', models.CharField(max_length=30)),
                ('bike_volume', models.IntegerField()),
                ('biker_city', models.CharField(max_length=30)),
            ],
        ),
    ]
